language: node_js
node_js: 
  - "10.13.0"
env:
  global:
    - NODE_ENV=test
    - SECRET_KEY=traeghiteslozae
    - DB_USERNAME=codeblock
    - DB_PASSWORD=codekey
    - DBNAME=bankr_testdb
    - MAIL_HOST=smtp.gmail.com
    - MAIL_PORT=465
    - MAIL_ENCRYPTION=true
    - MAIL_USERNAME=notifications.bankr@gmail.com
    - MAIL_PASSWORD=secureencryption@!.
services:
- postgresql
before_script:
- psql -c 'create database bankr_testdb;' -U postgres
- psql -c "CREATE USER codeblock WITH PASSWORD 'codekey';" -U postgres
cache:
  directories:
    - "node_modules"
script: npm test
after_success: 'npm run coverage'
after_failure: 'cat /home/travis/.npm/_logs/2019-04-*-debug.log'
