const actions = `CREATE TABLE IF NOT EXISTS actions(
  id SERIAL PRIMARY KEY,
  type VARCHAR(50) NOT NULL,
  owner INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  admin INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)`;

export default actions;
