const actions = `CREATE TABLE IF NOT EXISTS actions(
  id SERIAL PRIMARY KEY,
  firstName VARCHAR(50) NOT NULL,
  lastName VARCHAR(50) NOT NULL,
  role VARCHAR(20) NOT NULL,
  type VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  admin INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)`;

export default actions;
