const transactions = `CREATE TABLE IF NOT EXISTS transactions(
  id SERIAL PRIMARY KEY,
  accountNumber INTEGER NOT NULL,
  type VARCHAR(100) NOT NULL,
  account INTEGER REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE,
  owner INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  cashier INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  amount FLOAT NOT NULL,
  oldBalance FLOAT NOT NULL,
  newBalance FLOAT NOT NULL,
  createdOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)`;

export default transactions;
